site_name: MArray

nav:
  - Introduction: index.md
  - 'API Documentation': api.md

repo_url: https://github.com/devinamatthews/marray/

edit_uri: ''

use_directory_urls: false

docs_dir: doc/mkdocs/docs

site_dir: doc/mkdocs/site

theme:
  name: readthedocs
  highlightjs: true

#plugins:
#  - doxygen:
#      packages:
#        - doxygen:
#            url : doc/doxygen

