version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: 'apt-get update && apt-get install -y gcc-8 g++-8 make'
      - run:
          name: Configuring
          command: './configure CC=gcc-8 CXX=g++-8'
      - run:
          name: Building
          command: 'make'
      - run:
          name: Unit Testing
          command: './bin/test'
