version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Configuring
          command: './configure'
      - run:
          name: Building
          command: 'make'
      - run:
          name: Unit Testing
          command: './bin/test'
