version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: 'cimg/base:2021.10'
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: 'sudo apt-get update && sudo apt-get install -y clang llvm-dev libclang-dev make'
      - run:
          name: Configuring
          command: './configure CC=clang CXX=clang++ --enable-code-coverage'
      - run:
          name: Building
          command: 'make -j2'
      - run:
          name: Unit Testing
          command: './bin/run_tests.sh'
      - codecov/upload
